### PR TITLE
Automate website build

### PR DESCRIPTION
**Pull request by wlandau**
This PR automates the rendering of the website. After merging, it should render on GitHub Actions and deploy to the `gh-pages` branch.

### CODE REVIEW

**Comment by wlandau** [comment]
I see there are merge conflicts, so feel free to just grab the `.github/workflows/render.yaml` file and delete `docs` from `main`.

**Comment by wlandau** [comment]
Fixed the merge conflicts just now.

**Comment by wlandau** [comment]
Thanks for incorporating the YAML

**Comment by shikokuchuo** [comment]
Thanks, I put though a commit listing you as co-author instead. The pages render slightly different on gh-pages vs. on my machine. More convenient for sure, but a but less control.

**Pull request closed without merging**
