### PR TITLE
Embed tutorial video

### PR DESCRIPTION
**Pull request by wlandau**
@shikokuchuo, this PR embeds a 2-minute video showing how to use the GitHub UI to contribute packages.

### CODE REVIEW

**Comment by wlandau** [comment]
The video itself is at https://vimeo.com/923333903.

**Review by shikokuchuo — APPROVED** [review]
Thanks! That was very quick work!

I'll merge this first.

Just some suggestions:
- could be shortened by hovering mouse, maybe a shimmer and pause before pressing the buttons rather than the circling motion
- Just leave the default Create ..., seems an unnecessary extra step to actually change the PR title to 'Add'

**Comment by shikokuchuo** [comment]
It really looks good on the site though!

@eitsupi FYI video instructions now live at https://r-releases.github.io/contributors

**Comment by wlandau** [comment]
Great suggestions. I got the video down to exactly 1 minute, and the new version is posted. I'll go ahead and change "2-minute video" to "1-minute video" in the description.

**Pull request merged**
